FORMAT: 1A
HOST: https://api.music.apple.com/v1/

# Apple Music

Polls is a simple API allowing consumers to view polls and vote in them.

# Group General 

## Charts [/v1/catalog/{storefront}/charts]

+ Parameters

    + storefront: us (string) - Countrycode of Storefront to fetch

### Get CFirstatalog charts [GET]

+ Request

    + Headers

            Authorization: Bearer {token}